import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "../components/ui/themeprovider";
import Navbar from "./components/navbar";
import AuthProvider from "./components/Authprovider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "AI FORMS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <AuthProvider>
            {children}
            </AuthProvider>
        </ThemeProvider>
        </body>
    </html>
  );
}
